name: NodeJS with Webpack

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16.3.0'
      - name: build-next-js
        working-directory:  ./client
        run: |
          npm install
          npm run build
        
